name: Java CI 03.2 for compile sources
run-name: ${{ github.actor }} runs compile sources 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            database-server
            cache-server
            api
            
